### ISSUE TITLE
Refactor code: Move call to Ansible Playbook in Method

### ISSUE THREAD

**Issue by linuswagner** [atlarge-research/continuum#10]
Currently, every call to an Ansible playbook takes 6 lines to construct the command, plus an additional call to execute the command.  
Because playbooks are executed frequently through the code and only one thing, the path to the playbook, changes, this creates a lot of code duplication which makes methods longer and harder to read.

I propose, we introduce a method that takes a single mandatory argument (path to the playbook) to eliminate this problem

**Comment by matthijssjansen** [comment]
Thank you for the suggestion.
This is already implemented in the controlplane branch: the function that you describe exists, but I don't know if it is called in all parts of the framework, that I have to check later.

I am slowly merging controlplane into main, so you should see it soon.
