### ISSUE TITLE
Cite repository with ease

### ISSUE THREAD

**Issue by linuswagner** [atlarge-research/continuum#2]
You can add a CITATION.cff file to a repository to cite a repository easier.  
https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository

This might be interesting to look into

**Comment by matthijssjansen** [comment]
I didn't know this exist, it looks very interesting.
That being said, the CITATION.cff is only for citing software or datasets, but this repository is part of scientific work so I prefer people citing it using the provided Bibtex entry.
